export const tracks = [
  {
    id: "city-rain",
    audioUrl: "/api/media/tracks/city-rain.mp3",
    title: "ЧУГУН",
    artist: "1337, СИМОЧКА",
    durationSec: 222,
    explicit: false,
    cover: "linear-gradient(135deg, #5f739f 0%, #9ab2ff 50%, #22324d 100%)",
    tags: ["ambient", "late-night"],
  },
  {
    id: "poison-halo",
    audioUrl: "/api/media/tracks/poison-halo.mp3",
    title: "вода",
    artist: "1337, Locura",
    durationSec: 161,
    explicit: false,
    cover: "linear-gradient(135deg, #35559c 0%, #86a3e9 42%, #1c2746 100%)",
    tags: ["electronic", "focus"],
  },
  {
    id: "sleep-mode",
    audioUrl: "/api/media/tracks/sleep-mode.mp3",
    title: "воздух",
    artist: "1337, Locura",
    durationSec: 190,
    explicit: true,
    cover: "linear-gradient(135deg, #9b9998 0%, #c5c2bb 35%, #212226 100%)",
    tags: ["dark-pop", "trending"],
  },
  {
    id: "cloud-district",
    audioUrl: "/api/media/tracks/cloud-district.mp3",
    title: "CODE1",
    artist: "deadmanstok, fifhficjuro",
    durationSec: 176,
    explicit: false,
    cover: "linear-gradient(135deg, #8f83c9 0%, #c9c1ee 36%, #3a315a 100%)",
    tags: ["chill", "synth"],
  },
  {
    id: "close-to-fire",
    audioUrl: "/api/media/tracks/close-to-fire.mp3",
    title: "I DONT",
    artist: "Joji",
    durationSec: 202,
    explicit: false,
    cover: "linear-gradient(135deg, #f28f6e 0%, #f8d0a5 44%, #7a3b2f 100%)",
    tags: ["rnb", "popular"],
  },
  {
    id: "cobalt",
    audioUrl: "/api/media/tracks/cobalt.mp3",
    title: "Дискеты",
    artist: "J. Cole",
    durationSec: 154,
    explicit: true,
    cover: "linear-gradient(135deg, #e99f7d 0%, #d67f61 45%, #6f83a9 100%)",
    tags: ["hip-hop", "popular"],
  },
  {
    id: "after-glow",
    audioUrl: "/api/media/tracks/after-glow.mp3",
    title: "Born From a Wish",
    artist: "tuborosho",
    durationSec: 188,
    explicit: false,
    cover: "linear-gradient(135deg, #6b6391 0%, #b7aed4 42%, #2d2b3d 100%)",
    tags: ["indie", "discover"],
  },
  {
    id: "hotel-california",
    audioUrl: "/api/media/tracks/hotel-california.mp3",
    title: "DANCESIDE",
    artist: "Joji",
    durationSec: 129,
    explicit: true,
    cover: "linear-gradient(135deg, #3b1112 0%, #8a2f2a 55%, #111112 100%)",
    tags: ["trending", "new"],
  },
  {
    id: "two-six",
    audioUrl: "/api/media/tracks/two-six.mp3",
    title: "Chance",
    artist: "17jgm8THiQmza9TQs0UajM",
    durationSec: 196,
    explicit: true,
    cover: "linear-gradient(135deg, #e99f7d 0%, #d67f61 45%, #6f83a9 100%)",
    tags: ["hip-hop", "new"],
  },
  {
    id: "y-si-peleamos",
    audioUrl: "/api/media/tracks/y-si-peleamos.mp3",
    title: "FRAGILE",
    artist: "5MOcdMulPi5vpiKNDDUJoi",
    durationSec: 192,
    explicit: false,
    cover: "linear-gradient(135deg, #504c53 0%, #6e686f 45%, #252428 100%)",
    tags: ["latin", "new"],
  },
  {
    id: "cry",
    audioUrl: "/api/media/tracks/cry.mp3",
    title: "Hatestreakk",
    artist: "7wZlQiaVkYg7kiadfqFNpX",
    durationSec: 187,
    explicit: false,
    cover: "linear-gradient(135deg, #cb3f45 0%, #d6635d 45%, #4e2824 100%)",
    tags: ["pop", "new"],
  },
  {
    id: "homewrecker",
    audioUrl: "/api/media/tracks/homewrecker.mp3",
    title: "sv moscow",
    artist: "королевский XVII",
    durationSec: 209,
    explicit: false,
    cover: "linear-gradient(135deg, #9b9998 0%, #c5c2bb 35%, #212226 100%)",
    tags: ["dark-pop", "new"],
  },
  {
    id: "cook",
    audioUrl: "/api/media/tracks/cook.mp3",
    title: "ПО ПРИЧИНЕ УВАЖИТЕЛЬНОЙ",
    artist: "Sofi Tukker, J Balvin",
    durationSec: 170,
    explicit: false,
    cover: "linear-gradient(135deg, #87caf7 0%, #bbebfe 35%, #5e777f 100%)",
    tags: ["electronic", "new"],
  },
  {
    id: "die-for-me",
    audioUrl: "/api/media/tracks/die-for-me.mp3",
    title: "Anonymous Ember ☢️ХУЙ ТЕРМИНАТОР☢️ telegram @painhubmedia",
    artist: "ZAYN",
    durationSec: 180,
    explicit: true,
    cover: "linear-gradient(135deg, #787d81 0%, #a3a7ab 36%, #4f5358 100%)",
    tags: ["pop", "new"],
  },
  {
    id: "time-after-time",
    audioUrl: "/api/media/tracks/time-after-time.mp3",
    title: "SO SWAG",
    artist: "dekma, dmtboy",
    durationSec: 168,
    explicit: false,
    cover: "linear-gradient(135deg, #deb0a2 0%, #f0cbb6 40%, #7e6153 100%)",
    tags: ["pop", "new"],
  },
];

export const quickActions = [
  {
    id: "wave",
    title: "Моя волна",
    subtitle: "Обновлено только что",
    accent: "linear-gradient(135deg, #ffe192 0%, #dd8b42 100%)",
  },
  {
    id: "liked",
    title: "Любимые треки",
    subtitle: "Синхронизировано с плеером",
    accent: "linear-gradient(135deg, #f58ba8 0%, #93426c 100%)",
  },
  {
    id: "new",
    title: "Новые релизы",
    subtitle: "37 сегодня",
    accent: "linear-gradient(135deg, #9fe0ff 0%, #4264a8 100%)",
  },
  {
    id: "energy",
    title: "Энергия дня",
    subtitle: "Быстрый микс",
    accent: "linear-gradient(135deg, #b8ffb7 0%, #348a5b 100%)",
  },
];

export const showcases = [
  {
    id: "night-drive",
    playlistId: "pl-night-drive",
    title: "Night Drive",
    subtitle: "Электроника, синты",
    cover: "linear-gradient(135deg, #35559c 0%, #86a3e9 42%, #1c2746 100%)",
  },
  {
    id: "soft-heat",
    playlistId: "pl-soft-heat",
    title: "Soft Heat",
    subtitle: "Чилл и R&B",
    cover: "linear-gradient(135deg, #f28f6e 0%, #f8d0a5 44%, #7a3b2f 100%)",
  },
  {
    id: "noir-beat",
    playlistId: "pl-fresh",
    title: "Noir Beat",
    subtitle: "Темный поп",
    cover: "linear-gradient(135deg, #8f83c9 0%, #c9c1ee 36%, #3a315a 100%)",
  },
  {
    id: "city-warmth",
    playlistId: "pl-energy",
    title: "City Warmth",
    subtitle: "Инди и фанк",
    cover: "linear-gradient(135deg, #ffd763 0%, #f8a89e 42%, #6f384c 100%)",
  },
  {
    id: "violet-noise",
    playlistId: "pl-fresh",
    title: "Violet Noise",
    subtitle: "Нео-поп и дрим",
    cover: "linear-gradient(135deg, #c2a5ff 0%, #7d79e8 45%, #2f2f67 100%)",
  },
];

export const searchCollections = [
  {
    id: "winter",
    title: "Зимняя",
    gradient: "linear-gradient(135deg, #26375f 0%, #4b6e9d 45%, #a9b9cc 100%)",
  },
  {
    id: "mood",
    title: "Настроения",
    gradient: "linear-gradient(135deg, #f35d1f 0%, #e48f2d 42%, #f4cdd9 100%)",
  },
  {
    id: "kz",
    title: "Популярно в Казахстане",
    gradient: "linear-gradient(135deg, #89ff5e 0%, #c3ffc7 22%, #2f2f35 100%)",
  },
  {
    id: "workout",
    title: "Занятия",
    gradient: "linear-gradient(135deg, #dc3a18 0%, #f88a2a 38%, #96c7ff 100%)",
  },
  {
    id: "genres",
    title: "Жанры",
    gradient: "linear-gradient(135deg, #fde64b 0%, #f7a5a7 52%, #f49dd3 100%)",
  },
];

export const playlists = [
  {
    id: "pl-night-drive",
    title: "Night Drive",
    subtitle: "Электроника, синты",
    cover: "linear-gradient(135deg, #35559c 0%, #86a3e9 42%, #1c2746 100%)",
    trackIds: ["city-rain", "poison-halo", "cloud-district", "time-after-time"],
  },
  {
    id: "pl-soft-heat",
    title: "Soft Heat",
    subtitle: "Чилл и R&B",
    cover: "linear-gradient(135deg, #f28f6e 0%, #f8d0a5 44%, #7a3b2f 100%)",
    trackIds: ["close-to-fire", "homewrecker", "die-for-me", "after-glow"],
  },
  {
    id: "pl-energy",
    title: "Energy Day",
    subtitle: "Тренировка и ритм",
    cover: "linear-gradient(135deg, #89ff5e 0%, #3bbf79 45%, #17352d 100%)",
    trackIds: ["cook", "cobalt", "two-six", "cry"],
  },
  {
    id: "pl-fresh",
    title: "Fresh Radar",
    subtitle: "Новые релизы недели",
    cover: "linear-gradient(135deg, #f7d255 0%, #f3a2c5 44%, #5f3656 100%)",
    trackIds: ["hotel-california", "two-six", "cook", "die-for-me", "time-after-time"],
  },
];

export const artists = [
  { id: "a-synthlove", name: "synthlove", followers: "96K" },
  { id: "a-arivox", name: "Ari Vox", followers: "54K" },
  { id: "a-morphinevibe", name: "morphinevibe", followers: "71K" },
  { id: "a-joji", name: "Joji", followers: "2.4M" },
  { id: "a-jcole", name: "J. Cole", followers: "3.1M" },
  { id: "a-easykid", name: "Easykid", followers: "1.3M" },
  { id: "a-kali-uchis", name: "Kali Uchis", followers: "2.2M" },
  { id: "a-charlie-puth", name: "Charlie Puth", followers: "4.6M" },
  { id: "a-kenny-g", name: "Kenny G", followers: "980K" },
  { id: "a-zayn", name: "ZAYN", followers: "1.1M" },
  { id: "a-sombr", name: "sombr", followers: "420K" },
  { id: "a-tuborosho", name: "tuborosho", followers: "180K" },
  { id: "a-sofi-tukker", name: "Sofi Tukker", followers: "1.9M" },
  { id: "a-j-balvin", name: "J Balvin", followers: "5.3M" },
  { id: "a-ejae", name: "EJAE", followers: "240K" },
];

export const artistReleases = [
  {
    id: "rel-joji-nocturnal",
    artistId: "a-joji",
    title: "Nocturnal Hearts",
    type: "album",
    year: 2025,
    cover: "linear-gradient(135deg, #6a2f34 0%, #b34a46 42%, #1f1216 100%)",
    trackIds: ["hotel-california", "close-to-fire"],
  },
  {
    id: "rel-joji-nightglass",
    artistId: "a-joji",
    title: "Nightglass",
    type: "ep",
    year: 2024,
    cover: "linear-gradient(135deg, #3b1112 0%, #8a2f2a 55%, #111112 100%)",
    trackIds: ["hotel-california"],
  },
  {
    id: "rel-joji-close-to-fire",
    artistId: "a-joji",
    title: "Close To Fire",
    type: "single",
    year: 2023,
    cover: "linear-gradient(135deg, #f28f6e 0%, #f8d0a5 44%, #7a3b2f 100%)",
    trackIds: ["close-to-fire"],
  },
  {
    id: "rel-jcole-twilight-code",
    artistId: "a-jcole",
    title: "Twilight Code",
    type: "album",
    year: 2025,
    cover: "linear-gradient(135deg, #e99f7d 0%, #d67f61 45%, #6f83a9 100%)",
    trackIds: ["cobalt", "two-six"],
  },
  {
    id: "rel-jcole-urban-draft",
    artistId: "a-jcole",
    title: "Urban Draft",
    type: "ep",
    year: 2024,
    cover: "linear-gradient(135deg, #a97863 0%, #d69b7b 45%, #384b66 100%)",
    trackIds: ["cobalt"],
  },
  {
    id: "rel-jcole-two-six",
    artistId: "a-jcole",
    title: "Two Six",
    type: "single",
    year: 2024,
    cover: "linear-gradient(135deg, #d18a69 0%, #edaf8f 45%, #44506f 100%)",
    trackIds: ["two-six"],
  },
  {
    id: "rel-zayn-night-signal",
    artistId: "a-zayn",
    title: "Night Signal",
    type: "album",
    year: 2024,
    cover: "linear-gradient(135deg, #787d81 0%, #a3a7ab 36%, #4f5358 100%)",
    trackIds: ["die-for-me"],
  },
  {
    id: "rel-zayn-die-for-me",
    artistId: "a-zayn",
    title: "Die For Me",
    type: "single",
    year: 2025,
    cover: "linear-gradient(135deg, #6e7378 0%, #9ea2a7 36%, #3f4348 100%)",
    trackIds: ["die-for-me"],
  },
  {
    id: "rel-sombr-zero-light",
    artistId: "a-sombr",
    title: "Zero Light",
    type: "album",
    year: 2025,
    cover: "linear-gradient(135deg, #9b9998 0%, #c5c2bb 35%, #212226 100%)",
    trackIds: ["homewrecker", "sleep-mode"],
  },
  {
    id: "rel-sombr-shadowpack",
    artistId: "a-sombr",
    title: "Shadowpack",
    type: "ep",
    year: 2024,
    cover: "linear-gradient(135deg, #7f7d7d 0%, #b4b2ac 35%, #222326 100%)",
    trackIds: ["sleep-mode"],
  },
  {
    id: "rel-sombr-homewrecker",
    artistId: "a-sombr",
    title: "Homewrecker",
    type: "single",
    year: 2023,
    cover: "linear-gradient(135deg, #909090 0%, #c0bdb8 35%, #2a2b2e 100%)",
    trackIds: ["homewrecker"],
  },
  {
    id: "rel-tuborosho-signal-lane",
    artistId: "a-tuborosho",
    title: "Signal Lane",
    type: "ep",
    year: 2025,
    cover: "linear-gradient(135deg, #6b6391 0%, #b7aed4 42%, #2d2b3d 100%)",
    trackIds: ["after-glow"],
  },
  {
    id: "rel-tuborosho-after-glow",
    artistId: "a-tuborosho",
    title: "after glow",
    type: "single",
    year: 2024,
    cover: "linear-gradient(135deg, #7c73a5 0%, #c4bbdf 42%, #343149 100%)",
    trackIds: ["after-glow"],
  },
];

export const historySeeds = ["hotel-california", "cobalt", "city-rain", "after-glow", "cook", "die-for-me"];

export const initialQueue = [
  "city-rain",
  "poison-halo",
  "sleep-mode",
  "cloud-district",
  "close-to-fire",
  "cobalt",
  "after-glow",
];

export const initialLikedIds = ["city-rain", "close-to-fire", "cobalt", "homewrecker"];

export const vibeTags = ["Late Night", "Focus", "Trap Soul", "Guitar", "Ambient", "Pop"];

